/**
 * Reconciliation against `financetools`.
 *
 * The migration is trusted because recomputed totals match Access's own query
 * exactly, twenty years running (working doc §8.3). This port is held to the
 * same standard for the same reason: an independent implementation exists, so
 * "probably faithful" would be a choice rather than a limitation.
 *
 * The fixture holds complete schedules — every installment of every loan under
 * every strategy — generated by running the Python, under *both* rounding
 * modes. The port is checked against the half-even run, which holds the
 * rounding convention constant and so tests the algorithm and nothing else.
 * What the convention itself costs is measured separately, in `rounding.test.ts`.
 *
 * Regenerate with `pnpm --filter @varve/loans fixtures`.
 */

import { describe, expect, it } from 'vitest';
import { Money } from '@varve/core';
import { amortize, minimumPayment } from '../src/amortize.js';
import { repay, type MinimumMode, type Strategy } from '../src/strategy.js';
import fixture from './fixtures/financetools.json' with { type: 'json' };
import { PYTHON_STRATEGY, renderInstallments, toTerms, MINIMUM_MODE } from './oracle.js';

const money = (value: string) => Money.fromString(value);

/**
 * Ordered strategies pile the whole remainder onto one loan and never split it,
 * so there is nothing for the allocation correction (§11.5) to touch. These
 * must agree with the oracle line for line.
 */
const ORDERED: readonly Strategy[] = ['avalanche', 'blizzard', 'snowball'];
const SPREADING: readonly Strategy[] = ['cascade', 'ice-slide'];

const oracle = fixture.half_even;

describe('single-loan schedules, line for line', () => {
  for (const c of oracle.schedules) {
    it(`${c.name}`, () => {
      const schedule = amortize(toTerms(c.terms), {
        payment: money(c.payment),
        ...(c.months_requested === null ? {} : { maxMonths: c.months_requested }),
      });

      expect(renderInstallments(schedule.installments)).toEqual(c.installments);
      expect(schedule.finalBalance.toString()).toBe(money(c.final_balance).toString());
    });
  }

  it('derives the same scheduled payment from the annuity formula', () => {
    for (const c of oracle.schedules) {
      expect(minimumPayment(toTerms(c.terms)).toString()).toBe(money(c.minimum_payment).toString());
    }
  });
});

describe('ordered strategies, line for line', () => {
  for (const q of oracle.queues) {
    const loans = q.loans.map(toTerms);
    const minimum = MINIMUM_MODE[q.minimum as keyof typeof MINIMUM_MODE] as MinimumMode;

    for (const strategy of ORDERED) {
      const expected = q.strategies[PYTHON_STRATEGY[strategy] as keyof typeof q.strategies];

      describe(`${q.name} · ${strategy}`, () => {
        const actual = repay(loans, { strategy, budget: money(q.budget), minimum });

        it('takes the same number of months, and the same number of payments', () => {
          expect(actual.months).toBe(expected.duration);
          expect(actual.payments).toBe(expected.num_payments);
        });

        it('pays the same interest and principal, to the cent', () => {
          expect(actual.interestPaid.toString()).toBe(money(expected.interest_paid).toString());
          expect(actual.principalPaid.toString()).toBe(money(expected.principal_paid).toString());
        });

        it('settles on the same loan ordering', () => {
          expect(actual.schedules.map((s) => s.terms.title)).toEqual(expected.order);
        });

        it('matches every installment of every loan', () => {
          for (const loan of expected.loans) {
            const got = actual.schedules.find((s) => s.terms.title === loan.title);
            expect(got, `no schedule for ${loan.title}`).toBeDefined();
            expect(renderInstallments(got!.installments), loan.title).toEqual(loan.installments);
          }
        });
      });
    }
  }
});

/**
 * Cascade and ice slide are the two that *should* differ, because they are the
 * two that split a remainder. The Python rounds each loan's share on its own, so
 * the shares need not add up to the budget; the port allocates by largest
 * remainder instead, and spends exactly what it was given. `budget.test.ts`
 * asserts the correction directly — here we only pin how far it can move things.
 */
describe('spreading strategies diverge only as far as the correction reaches', () => {
  for (const q of oracle.queues) {
    const loans = q.loans.map(toTerms);
    const minimum = MINIMUM_MODE[q.minimum as keyof typeof MINIMUM_MODE] as MinimumMode;

    for (const strategy of SPREADING) {
      const expected = q.strategies[PYTHON_STRATEGY[strategy] as keyof typeof q.strategies];
      const actual = repay(loans, { strategy, budget: money(q.budget), minimum });

      describe(`${q.name} · ${strategy}`, () => {
        it('retires the debt in the same number of months', () => {
          expect(actual.months).toBe(expected.duration);
        });

        it('stays within the cent-per-payment the reallocation can move', () => {
          const drift = actual.interestPaid.minus(money(expected.interest_paid)).abs();
          expect(drift.toNumber()).toBeLessThanOrEqual(actual.payments * 0.01);
        });

        it('repays the same principal — the debt is the debt', () => {
          expect(actual.principalPaid.toString()).toBe(money(expected.principal_paid).toString());
        });
      });
    }
  }
});

describe('the fixture itself', () => {
  it('covers enough ground to mean something', () => {
    const lines =
      oracle.schedules.reduce((n, s) => n + s.installments.length, 0) +
      oracle.queues.reduce(
        (n, q) =>
          n +
          Object.values(q.strategies).reduce(
            (m, s) => m + s.loans.reduce((k, l) => k + l.installments.length, 0),
            0,
          ),
        0,
      );

    expect(lines).toBeGreaterThan(2_000);
  });

  it('quotes every rate in two decimal places or fewer', () => {
    // The Python rounds the rate through its money helper, so a third decimal
    // place would make the oracle disagree with the port and be wrong to. §11.3.
    const rates = [
      ...oracle.schedules.map((s) => s.terms.annual_rate_percent),
      ...oracle.queues.flatMap((q) => q.loans.map((l) => l.annual_rate_percent)),
    ];
    for (const rate of rates) {
      expect(Number(rate) * 100).toBe(Math.round(Number(rate) * 100));
    }
  });
});

describe('every loan in the fixture is invented', () => {
  it('carries no name that could belong to anyone', () => {
    // Ground rule 1, applied where it is cheap rather than only where it is
    // critical. Nothing here came from a real statement.
    const titles = [
      ...oracle.schedules.map((s) => s.terms.title),
      ...oracle.queues.flatMap((q) => q.loans.map((l) => l.title)),
    ];
    expect(titles.every((t) => /^[A-Za-z0-9 ,'()-]+$/.test(t))).toBe(true);
    expect(new Set(titles).size).toBeGreaterThan(5);
  });
});
